language: ruby
rvm:
  - 1.9.2
services:
  - postgresql
before_script:
  - psql -c 'create database keymaster_test;' -U postgres
  - cp config/database.ci.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:setup
bundler_args: --without=development
notifications:
  email: false
